# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: "chief medical officer"
  description: Conduct medical triage and surgery when necessary. Decide who should be saved, and when.
  head: true
  startingGear: CMOGear
  allegiances:
  - Command
  - Medical
  icon: "ChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    id: CMOPDA
    ears: ClothingHeadsetAltMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
