- type: job
  id: Pharmacist
  name: "pharmacist"
  description: Make medicine and pharmaceuticals for the station. Your skills may come in handy in other places, if you can find buyers.
  startingGear: ChemistGear
  allegiances:
  - Medical
  icon: "Chemist"
  supervisors: "the chief medical officer"
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedical
    pocket1: HandLabeler
    # the purple glasses?
  innerclothingskirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
