- type: job
  id: Practitioner
  name: "practitioner"
  description: Administer medical treatment. Help locate and retrieve dead bodies--better yet, before they die at all.
  startingGear: DoctorGear
  allegiances:
  - Medical
  icon: "MedicalDoctor"
  supervisors: "the chief medical officer"
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: DoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: MedicalPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtMedicalDoctor
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
