- type: job
  id: Captain
  name: "captain"
  description: You're what this is all about, baby. Pilot your ship into the great unknown and come back a hero.
  head: true
  startingGear: CaptainGear
  allegiances:
  - Command
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: "Antares officials"
  canBeAntag: false
  access:
  # All of em.
  # Could probably do with some kind of wildcard or whatever to automate this.
  # HELL FUCKING YEAH WE COULD
  # Guys please don't fight
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Command
  - Security
  - Armory
 # - Brig
  - Engineering
  - Medical
  - Cargo
  - Research
  - Service
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterHardsuitCap
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
