- type: job
  id: HeadOfPersonnel
  name: "head of personnel"
  description: The captain may call themselves the "executive authority", but you're the real person in charge. Keep all the departments in ship shape and help coordinate efforts.
  startingGear: HoPGear
  allegiances:
  - Command
  - Civilian
  icon: "HeadOfPersonnel"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Security # HoPcurity strikes again
  - Service
  - Cargo
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  # I mean they'll give themselves the rest of the access levels *anyways*.

- type: startingGear
  id: HoPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
