- type: job
  id: Janitor
  name: "janitor"
  startingGear: JanitorGear
  departments:
  - Security
  icon: "Janitor"
  supervisors: "the head of security"
  access:
  - Janitor
  - Maintenance
  - Security
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: RevolverInspector

- type: startingGear
  id: JanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJanitor
    back: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatPurplesoft
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerclothingskirt: ClothingUniformJumpskirtJanitor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
