- type: job
  id: Mechanic
  name: "mechanic"
  description: Keep the machines on the station running nicely, fix hull breaches and sabotage attempts, and renovate.
  startingGear: StationEngineerGear
  allegiances:
  - Engineering
  icon: "StationEngineer"
  supervisors: "the chief engineer"
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: StationEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    id: EngineerPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
