- type: job
  id: PowerTechnician
  name: "power technician"
  description: Feed the Singularity. Maximize efficiency on the powernet.
  startingGear: StationEngineerGear
  allegiances:
  - Engineering
  icon: "StationEngineer"
  supervisors: "the chief engineer"
  access:
  - Maintenance
  - Engineering
  - External
