- type: job
  id: Quartermaster
  name: "quartermaster"
  startingGear: QuartermasterGear
  description: Keep tabs on everything. Yell at your workers. Don't let anyone shady into the warehouse.
  allegiances:
  - Logistics
  icon: "QuarterMaster"
  supervisors: "the head of personnel"
  access:
  - Cargo
 # - Quartermaster
  - Maintenance
  - External

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetCargo
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
