- type: job
  id: WarehouseWorker
  name: "warehouse worker"
  description: Do any errands asked of you by the Quartermaster. You may not be at the top of the totem pole, but you take pride in Logistics.
  startingGear: CargoTechGear
  allegiances:
  - Logistics
  icon: "CargoTechnician"
  supervisors: "the quartermaster"
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
  innerclothingskirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
