- type: job
  id: Clown
  name: "clown"
  description: You don't know why Antares recruited you, but you're here anyway. Do what you do best, space jester!
  startingGear: ClownGear
  allegiances:
  - Civilian
  - Inn
  icon: "Clown"
  supervisors: "the innkeeper"
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    component: Clumsy # Adds ClumsyComponent to the mob.

- type: startingGear
  id: ClownGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackClownFilled
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    pocket1: BikeHorn
    id: ClownPDA
    ears: ClothingHeadsetService
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelClownFilled
