- type: job
  id: Preacher
  name: "preacher"
  startingGear: ChaplainGear
  departments:
  - Civilian
  icon: "Chaplain"
  supervisors: "absolutely everyone"
  access:
  - Chapel
  - Maintenance

- type: startingGear
  id: ChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
