- type: job
  id: Preacher
  name: "preacher"
  description: How can they not understand? Even if you are ridiculed in life, it is your prime directive to teach the ways that may one day save this damned universe.
  startingGear: ChaplainGear
  allegiances:
  - Undership
  icon: "Chaplain"
  supervisors: "absolutely everyone"
  access:
  - Chapel
  - Maintenance

- type: startingGear
  id: ChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtChaplain
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
