- type: job
  id: Stowaway
  name: "stowaway"
  startingGear: AssistantGear
  departments:
  - Civilian
  icon: "Assistant"
  supervisors: "absolutely everyone"
  access:
  - Maintenance

- type: startingGear
  id: AssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: AssistantPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
