- type: job
  id: Stowaway
  name: "stowaway"
  description: You aren't supposed to be here. Keep yourself inconspicuous, but you need to make a living somehow.
  startingGear: AssistantGear
  allegiances:
  - Undership
  icon: "Assistant"
  supervisors: "absolutely everyone"
  access:
  - Maintenance

- type: startingGear
  id: AssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: AssistantPDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
