- type: job
  id: Hydroponicist
  name: "hydroponicist"
  startingGear: BotanistGear
  departments:
  - Civilian
  icon: "Botanist"
  supervisors: "the research director"
  access:
  - Service
  - Maintenance
  - Hydroponics

- type: startingGear
  id: BotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
