- type: job
  id: Hydroponicist
  name: "hydroponicist"
  description: Nature is a beatiful thing. Keep the flora on this steel hell alive and useful, and study alien lifeforms.
  startingGear: BotanistGear
  allegiances:
  - Science
  icon: "Botanist"
  supervisors: "the research director"
  access:
  - Service
  - Maintenance
  - Hydroponics

- type: startingGear
  id: BotanistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponicsFilled
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
  innerclothingskirt: ClothingUniformJumpskirtHydroponics
  satchel: ClothingBackpackSatchelHydroponicsFilled
  duffelbag: ClothingBackpackDuffelFilled
