- type: job
  id: ResearchDirector
  name: "research director"
  description: This expedition would be nothing without you. Coordinate and focus the research efforts of the crew.
  head: true
  startingGear: ResearchDirectorGear
  allegiances:
  - Command
  - Science
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: "the captain"
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLab
    id: RnDPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
