- type: job
  id: Xenoarchaeologist
  name: "xenoarchaeologist"
  startingGear: ScientistGear
  departments:
  - Science
  icon: "Scientist"
  supervisors: "the research director"
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
